### ISSUE TITLE
HIT generation issues

### ISSUE THREAD

**Issue by erincandescent** [dmitriykuptsov/cutehip#2]
A couple of what I think are issues I spotted while taking a look at the code:

A general one: You're using the IPv6 prefix `2001:2000::/28` not `2001:0020::/28`. That tripped me up at first too - the canonical short form is confusing for this prefix

For RSA keys, on `utils/hi.py:66`, you check

```
		if exponent > 255:
```

This should be 
```
		if exponent_length > 255:
```

As is, for the common exponent 65537 you generate the overlong encoding `00 00 03 01 00 01 ...` instead of canonical `03 01 00 01 ...`

**Comment by erincandescent** [comment]
Also I think your HITs have the hash bytes flipped - by my reading "HIT.int_to_bytearray" accidentally outputs little endian values

**Comment by dmitriykuptsov** [comment]
> A couple of what I think are issues I spotted while taking a look at the code:
> 
> A general one: You're using the IPv6 prefix `2001:2000::/28` not `2001:0020::/28`. That tripped me up at first too - the canonical short form is confusing for this prefix

Thank you! I have fixed wrong prefix issue!

> 
> For RSA keys, on `utils/hi.py:66`, you check
> 
> ```
> 		if exponent > 255:
> ```
> 
> This should be
> 
> ```
> 		if exponent_length > 255:
> ```
> 
> As is, for the common exponent 65537 you generate the overlong encoding `00 00 03 01 00 01 ...` instead of canonical `03 01 00 01 ...`

I have fixed this bug too.
